# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import streaming_pb2 as streaming__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in streaming_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class StreamingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CriarUsuario = channel.unary_unary(
                '/streaming.StreamingService/CriarUsuario',
                request_serializer=streaming__pb2.UsuarioRequest.SerializeToString,
                response_deserializer=streaming__pb2.UsuarioResponse.FromString,
                _registered_method=True)
        self.ListarUsuarios = channel.unary_unary(
                '/streaming.StreamingService/ListarUsuarios',
                request_serializer=streaming__pb2.Empty.SerializeToString,
                response_deserializer=streaming__pb2.ListaUsuarios.FromString,
                _registered_method=True)
        self.AtualizarUsuario = channel.unary_unary(
                '/streaming.StreamingService/AtualizarUsuario',
                request_serializer=streaming__pb2.UpdateUsuarioRequest.SerializeToString,
                response_deserializer=streaming__pb2.UsuarioResponse.FromString,
                _registered_method=True)
        self.DeletarUsuario = channel.unary_unary(
                '/streaming.StreamingService/DeletarUsuario',
                request_serializer=streaming__pb2.IdRequest.SerializeToString,
                response_deserializer=streaming__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.ListarPlaylistsDoUsuario = channel.unary_unary(
                '/streaming.StreamingService/ListarPlaylistsDoUsuario',
                request_serializer=streaming__pb2.IdRequest.SerializeToString,
                response_deserializer=streaming__pb2.ListaPlaylists.FromString,
                _registered_method=True)
        self.CriarMusica = channel.unary_unary(
                '/streaming.StreamingService/CriarMusica',
                request_serializer=streaming__pb2.MusicaRequest.SerializeToString,
                response_deserializer=streaming__pb2.MusicaResponse.FromString,
                _registered_method=True)
        self.ListarMusicas = channel.unary_unary(
                '/streaming.StreamingService/ListarMusicas',
                request_serializer=streaming__pb2.Empty.SerializeToString,
                response_deserializer=streaming__pb2.ListaMusicas.FromString,
                _registered_method=True)
        self.AtualizarMusica = channel.unary_unary(
                '/streaming.StreamingService/AtualizarMusica',
                request_serializer=streaming__pb2.UpdateMusicaRequest.SerializeToString,
                response_deserializer=streaming__pb2.MusicaResponse.FromString,
                _registered_method=True)
        self.DeletarMusica = channel.unary_unary(
                '/streaming.StreamingService/DeletarMusica',
                request_serializer=streaming__pb2.IdRequest.SerializeToString,
                response_deserializer=streaming__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.ListarPlaylistsDaMusica = channel.unary_unary(
                '/streaming.StreamingService/ListarPlaylistsDaMusica',
                request_serializer=streaming__pb2.IdRequest.SerializeToString,
                response_deserializer=streaming__pb2.ListaPlaylists.FromString,
                _registered_method=True)
        self.CriarPlaylist = channel.unary_unary(
                '/streaming.StreamingService/CriarPlaylist',
                request_serializer=streaming__pb2.PlaylistRequest.SerializeToString,
                response_deserializer=streaming__pb2.PlaylistResponse.FromString,
                _registered_method=True)
        self.AtualizarPlaylist = channel.unary_unary(
                '/streaming.StreamingService/AtualizarPlaylist',
                request_serializer=streaming__pb2.UpdatePlaylistRequest.SerializeToString,
                response_deserializer=streaming__pb2.PlaylistResponse.FromString,
                _registered_method=True)
        self.DeletarPlaylist = channel.unary_unary(
                '/streaming.StreamingService/DeletarPlaylist',
                request_serializer=streaming__pb2.IdRequest.SerializeToString,
                response_deserializer=streaming__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.AddMusicaPlaylist = channel.unary_unary(
                '/streaming.StreamingService/AddMusicaPlaylist',
                request_serializer=streaming__pb2.AddMusicaRequest.SerializeToString,
                response_deserializer=streaming__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.ListarMusicasDaPlaylist = channel.unary_unary(
                '/streaming.StreamingService/ListarMusicasDaPlaylist',
                request_serializer=streaming__pb2.IdRequest.SerializeToString,
                response_deserializer=streaming__pb2.ListaMusicas.FromString,
                _registered_method=True)


class StreamingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CriarUsuario(self, request, context):
        """--- USUÁRIOS ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarUsuarios(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AtualizarUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletarUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarPlaylistsDoUsuario(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CriarMusica(self, request, context):
        """--- MÚSICAS ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarMusicas(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AtualizarMusica(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletarMusica(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarPlaylistsDaMusica(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CriarPlaylist(self, request, context):
        """--- PLAYLISTS ---
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AtualizarPlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletarPlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddMusicaPlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListarMusicasDaPlaylist(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_StreamingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CriarUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.CriarUsuario,
                    request_deserializer=streaming__pb2.UsuarioRequest.FromString,
                    response_serializer=streaming__pb2.UsuarioResponse.SerializeToString,
            ),
            'ListarUsuarios': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarUsuarios,
                    request_deserializer=streaming__pb2.Empty.FromString,
                    response_serializer=streaming__pb2.ListaUsuarios.SerializeToString,
            ),
            'AtualizarUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.AtualizarUsuario,
                    request_deserializer=streaming__pb2.UpdateUsuarioRequest.FromString,
                    response_serializer=streaming__pb2.UsuarioResponse.SerializeToString,
            ),
            'DeletarUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletarUsuario,
                    request_deserializer=streaming__pb2.IdRequest.FromString,
                    response_serializer=streaming__pb2.StatusResponse.SerializeToString,
            ),
            'ListarPlaylistsDoUsuario': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarPlaylistsDoUsuario,
                    request_deserializer=streaming__pb2.IdRequest.FromString,
                    response_serializer=streaming__pb2.ListaPlaylists.SerializeToString,
            ),
            'CriarMusica': grpc.unary_unary_rpc_method_handler(
                    servicer.CriarMusica,
                    request_deserializer=streaming__pb2.MusicaRequest.FromString,
                    response_serializer=streaming__pb2.MusicaResponse.SerializeToString,
            ),
            'ListarMusicas': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarMusicas,
                    request_deserializer=streaming__pb2.Empty.FromString,
                    response_serializer=streaming__pb2.ListaMusicas.SerializeToString,
            ),
            'AtualizarMusica': grpc.unary_unary_rpc_method_handler(
                    servicer.AtualizarMusica,
                    request_deserializer=streaming__pb2.UpdateMusicaRequest.FromString,
                    response_serializer=streaming__pb2.MusicaResponse.SerializeToString,
            ),
            'DeletarMusica': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletarMusica,
                    request_deserializer=streaming__pb2.IdRequest.FromString,
                    response_serializer=streaming__pb2.StatusResponse.SerializeToString,
            ),
            'ListarPlaylistsDaMusica': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarPlaylistsDaMusica,
                    request_deserializer=streaming__pb2.IdRequest.FromString,
                    response_serializer=streaming__pb2.ListaPlaylists.SerializeToString,
            ),
            'CriarPlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.CriarPlaylist,
                    request_deserializer=streaming__pb2.PlaylistRequest.FromString,
                    response_serializer=streaming__pb2.PlaylistResponse.SerializeToString,
            ),
            'AtualizarPlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.AtualizarPlaylist,
                    request_deserializer=streaming__pb2.UpdatePlaylistRequest.FromString,
                    response_serializer=streaming__pb2.PlaylistResponse.SerializeToString,
            ),
            'DeletarPlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletarPlaylist,
                    request_deserializer=streaming__pb2.IdRequest.FromString,
                    response_serializer=streaming__pb2.StatusResponse.SerializeToString,
            ),
            'AddMusicaPlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.AddMusicaPlaylist,
                    request_deserializer=streaming__pb2.AddMusicaRequest.FromString,
                    response_serializer=streaming__pb2.StatusResponse.SerializeToString,
            ),
            'ListarMusicasDaPlaylist': grpc.unary_unary_rpc_method_handler(
                    servicer.ListarMusicasDaPlaylist,
                    request_deserializer=streaming__pb2.IdRequest.FromString,
                    response_serializer=streaming__pb2.ListaMusicas.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'streaming.StreamingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('streaming.StreamingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class StreamingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CriarUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/CriarUsuario',
            streaming__pb2.UsuarioRequest.SerializeToString,
            streaming__pb2.UsuarioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarUsuarios(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/ListarUsuarios',
            streaming__pb2.Empty.SerializeToString,
            streaming__pb2.ListaUsuarios.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AtualizarUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/AtualizarUsuario',
            streaming__pb2.UpdateUsuarioRequest.SerializeToString,
            streaming__pb2.UsuarioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletarUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/DeletarUsuario',
            streaming__pb2.IdRequest.SerializeToString,
            streaming__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarPlaylistsDoUsuario(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/ListarPlaylistsDoUsuario',
            streaming__pb2.IdRequest.SerializeToString,
            streaming__pb2.ListaPlaylists.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CriarMusica(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/CriarMusica',
            streaming__pb2.MusicaRequest.SerializeToString,
            streaming__pb2.MusicaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarMusicas(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/ListarMusicas',
            streaming__pb2.Empty.SerializeToString,
            streaming__pb2.ListaMusicas.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AtualizarMusica(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/AtualizarMusica',
            streaming__pb2.UpdateMusicaRequest.SerializeToString,
            streaming__pb2.MusicaResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletarMusica(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/DeletarMusica',
            streaming__pb2.IdRequest.SerializeToString,
            streaming__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarPlaylistsDaMusica(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/ListarPlaylistsDaMusica',
            streaming__pb2.IdRequest.SerializeToString,
            streaming__pb2.ListaPlaylists.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CriarPlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/CriarPlaylist',
            streaming__pb2.PlaylistRequest.SerializeToString,
            streaming__pb2.PlaylistResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AtualizarPlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/AtualizarPlaylist',
            streaming__pb2.UpdatePlaylistRequest.SerializeToString,
            streaming__pb2.PlaylistResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletarPlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/DeletarPlaylist',
            streaming__pb2.IdRequest.SerializeToString,
            streaming__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddMusicaPlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/AddMusicaPlaylist',
            streaming__pb2.AddMusicaRequest.SerializeToString,
            streaming__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListarMusicasDaPlaylist(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/streaming.StreamingService/ListarMusicasDaPlaylist',
            streaming__pb2.IdRequest.SerializeToString,
            streaming__pb2.ListaMusicas.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
